spring:
  application:
    name: scrum-together-api

  datasource:
    url: ${SCRUMTOGETHER_DATABASE_URL}
    username: ${SCRUMTOGETHER_DATABASE_USERNAME}
    password: ${SCRUMTOGETHER_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      poll-interval: 1s
      quiet-period: 400ms
      additional-exclude: static/**,public/**
    livereload:
      enabled: true

logging:
  level:
    org.springframework: INFO
    fr.scrumtogether: DEBUG

security:
  jwt:
    secret-key: "AwesomeScrumTogetherSecretKey1WhichIsTheMostSECRETEverAwesomeScrumTogetherSecretKey1WhichIsTheMostSECRETEverAwesomeScrumTogetherSecretKey1WhichIsTheMostSECRETEverAwesomeScrumTogetherSecretKey1WhichIsTheMostSECRETEver"
    expiration-time: 864000


rate-limit:
  requests-per-minute: 2
  expiration-minutes: 15

brevo:
  api-key: ${BREVO_API_KEY}
  api-key-file: ${BREVO_API_KEY_FILE}
  scrum-together-folder-id: 2
  scrum-together-users-list-id: 4
  scrum-together-admins-list-id: 7