spring:
  application:
    name: scrum-together-api

  datasource:
    url: ${SCRUMTOGETHER_DATABASE_URL}
    username: ${SCRUMTOGETHER_DATABASE_USERNAME}
    password: ${SCRUMTOGETHER_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      poll-interval: 1s
      quiet-period: 400ms
      additional-exclude: static/**,public/**
    livereload:
      enabled: true

logging:
  level:
    org.springframework: DEBUG

security:
  jwt:
    secret-key: "AwesomeScrumTogetherSecretKey1WhichIsTheMostSECRETEverAwesomeScrumTogetherSecretKey1WhichIsTheMostSECRETEverAwesomeScrumTogetherSecretKey1WhichIsTheMostSECRETEverAwesomeScrumTogetherSecretKey1WhichIsTheMostSECRETEver"
    expiration-time: 864000